### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by ghost** [Yoplitein/WurmHelper#4]
Hi there,
I've been playing with your code trying to get it to compile. So far without success.
This is what the compiler spits back at me.

C:\Users\Val\Desktop\WurmHelper-upstream-dev\main\java\net\ildar\wurm\BotController.java:21:19
java: cannot find symbol
  symbol:   variable BotRegistrationProvider
  location: class net.ildar.wurm.BotController

What I have done is got the original project by IldarW and compiled that along with a couple of your initial submits. The part i'm having difficulty with is implementing the annotations portion.

Any help would be greatly appreciated.

**Comment by Yoplitein** [comment]
It sounds like you're trying to build without Maven -- understandable if you were looking at the `master` branch of upstream, the Maven setup only exists on the `dev` branch. With Maven, the build should be as simple as `mvn install` to generate the zip, or `mvn compile package` to generate just the jar.

**Comment by ghost** [comment]
Yep, i had no idea what maven was. Took me a little while to get it set up and sure enough, that was it.

Thanks btw!

**Comment by Valendine** [comment]
Besides figuring out how to run RMI, i'm very curious why you have the dev and the upstream "editions".
