### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by cake254** [Yoplitein/WurmHelper#9]
I have java, runtime, etc. Try to run it and nothing happens. Thanks

**Comment by Yoplitein** [comment]
Do you have other mods working? Does the `bot` command in console print anything?

**Comment by cake254** [comment]
I have nothing else running and just a clean install of wurm online. Tried putting the jar in different wurm directories and still nothing. Typing "bot" in the console and it doesn't recognize the command

**Comment by cake254** [comment]
If it's only for wurm unlimited, is it possible to make it work for wurm online? Maybe I can pay a coder?

**Comment by Yoplitein** [comment]
This is in fact only for Wurm Unlimited. I can also tell you that porting it to work with Wurm Online would be a herculean task given there's no mod loader and the codebases have diverged significantly. When WU was freshly released there were already a number of differences as they omitted certain code to keep secret e.g. how skillgain works, macroing detection, etc. And on the subject of macroing detection, use of this mod would flag your account immediately and I'm sure you would be banned very quickly. In the past I have triggered macroing detection just by efficient yet manual use of keybinds, so I can't imagine it would take long for GMs to notice you.
